
EMAIL_SUBJECT="Please verify your account"
ACCOUNT_DOES_NOT_EXISTS="Account does not exists"
PASSWORD_RESET_SUCCESS="Password Reset Success, Please Login"
EMAIL_FORGOT_PASSWORD="Please change your password"
LINK_EXPIRED="Link Expired"
EMAIL_VERIFY_SUCCESS="Email Verifaction Success"
EMAIL_SEND_TO_USER="Please Verify Email send to activate account"
USER_ALREADY_VERIFIED="User is already verified"
USER_ALREADY_REGISTERED="User already Registered, Please try to Login"
BLANK=""
SOMETHING_HAPPENED="Something happed, try again"
PASSWORD_MISMATCH="Passord didn't Match"
PLEASE_PROVIDE_USERNAME="Please Provide Social Name"
PLEASE_PROVIDE_PASSWORD="Please Provide Password"
PLEASE_VERIFY_EMAIL="Please verify email through mail link, we send lasttime"
PASSWORD_VALIDATIONS="Password MustContain 1 Capital, 1 Number, 1 Special character and 8>=length<28"
PASSWORD_WRONG="Password Wrong"
ACCOUNT_ALREADY_EXISTS="Email Account Already added"
ACCOUNT_ADDED="ACCOUNT ADDED"
DEFAULT_IMAGE="userprofiles/images.jpeg"
WRONG_CODE_OR_ALREADY_USED="Wrong code or Already used copon Code"
SLOT_SAVED="SLOT SAVED For You, You can View in My Appointments"
ERROR_IN_SLOT_SAVED="Unable to Book Slot for you "
SLOT_ALREADY_BOOKED="This Slot is Already Taken, Please chose Another"
APPOINTMENT_CANCEL_FAILED="Appoint Cancelation failed"
APPOINTMENT_CANCELD="Appointment Cancelled"
REFUND="Refund will happen with in 48 hours"