# Generated by Django 4.0.4 on 2022-06-17 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_appointmentdocuments_alter_clinic_createddate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('paymentorderId', models.CharField(default='', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('amount', models.IntegerField(default=0, max_length=100)),
                ('doctorbookingid', models.CharField(default='', max_length=1000)),
                ('doctorId', models.CharField(default='', max_length=1000)),
                ('userId', models.CharField(default='', max_length=1000)),
                ('createdDate', models.DateTimeField(default=datetime.datetime(2022, 6, 17, 10, 43, 10, 562282), verbose_name='Payment Last created At')),
                ('updatedDate', models.DateTimeField(default=datetime.datetime(2022, 6, 17, 10, 43, 10, 562294), verbose_name='Payment Last updated At')),
            ],
        ),
        migrations.AlterField(
            model_name='appointmentdocuments',
            name='documents',
            field=models.FileField(blank=True, upload_to='static/appointmentdocuments'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 10, 43, 10, 484935), verbose_name='Clinic created At'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='updatedDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 10, 43, 10, 484946), verbose_name='Clinic Last Updated At'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 10, 43, 10, 485956), verbose_name='Clinic created At'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='updatedDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 10, 43, 10, 485964), verbose_name='Clinic Last Updated At'),
        ),
        migrations.AlterField(
            model_name='doctorbooking',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 10, 43, 10, 487329), verbose_name='Slot created At'),
        ),
        migrations.AlterField(
            model_name='doctorbooking',
            name='updatedDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 10, 43, 10, 487339), verbose_name='Slot Last Updated At'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 10, 43, 10, 476850), verbose_name='Chat Last created At'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='updatedDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 10, 43, 10, 476862), verbose_name='Chat Last updated At'),
        ),
        migrations.AlterField(
            model_name='post',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 10, 43, 10, 473597), verbose_name='Post Last created At'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updatedDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 10, 43, 10, 473613), verbose_name='Post Last Updated At'),
        ),
        migrations.AlterField(
            model_name='postuploaddetails',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 10, 43, 10, 474712), verbose_name='Post Last created At'),
        ),
        migrations.AlterField(
            model_name='postuploaddetails',
            name='updatedDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 10, 43, 10, 474724), verbose_name='Post Last Updated At'),
        ),
        migrations.AlterField(
            model_name='user',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 10, 43, 10, 394845), verbose_name='User Created At'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastlogin',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 10, 43, 10, 394873), verbose_name='User Last LoggedIn At'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updatedDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 10, 43, 10, 394854), verbose_name='User Last Updated At'),
        ),
    ]
