# Generated by Django 4.0.4 on 2022-06-17 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_payment_alter_appointmentdocuments_documents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='refundStatus',
            field=models.BooleanField(default=0, verbose_name='Refund Status'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 11, 6, 20, 514549), verbose_name='Clinic created At'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='updatedDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 11, 6, 20, 514558), verbose_name='Clinic Last Updated At'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 11, 6, 20, 515058), verbose_name='Clinic created At'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='updatedDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 11, 6, 20, 515065), verbose_name='Clinic Last Updated At'),
        ),
        migrations.AlterField(
            model_name='doctorbooking',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 11, 6, 20, 515547), verbose_name='Slot created At'),
        ),
        migrations.AlterField(
            model_name='doctorbooking',
            name='updatedDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 11, 6, 20, 515556), verbose_name='Slot Last Updated At'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 11, 6, 20, 510595), verbose_name='Chat Last created At'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='updatedDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 11, 6, 20, 510603), verbose_name='Chat Last updated At'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 11, 6, 20, 570391), verbose_name='Payment Last created At'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updatedDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 11, 6, 20, 570403), verbose_name='Payment Last updated At'),
        ),
        migrations.AlterField(
            model_name='post',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 11, 6, 20, 509180), verbose_name='Post Last created At'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updatedDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 11, 6, 20, 509191), verbose_name='Post Last Updated At'),
        ),
        migrations.AlterField(
            model_name='postuploaddetails',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 11, 6, 20, 509618), verbose_name='Post Last created At'),
        ),
        migrations.AlterField(
            model_name='postuploaddetails',
            name='updatedDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 11, 6, 20, 509626), verbose_name='Post Last Updated At'),
        ),
        migrations.AlterField(
            model_name='user',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 11, 6, 20, 494848), verbose_name='User Created At'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastlogin',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 11, 6, 20, 494877), verbose_name='User Last LoggedIn At'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updatedDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 11, 6, 20, 494858), verbose_name='User Last Updated At'),
        ),
    ]
